language: node_js
node_js:
- 10.15.3
os:
- osx
notifications:
  email: false
  slack:
    rooms:
      - secure: fcmuyLTnHaC/KQA4KwJKJTuk7pk0/gbNcOJJ8p1lfLFt59ZSBezOKbatiJU6XuWH0y6zdKum8qnEIFfD5Iuj0PTKwzt1Miaep3w73kSo8UDxPQcb/TwNt5S+MOinPZrX21ZcTZ0N3iSB4l1RsgB6QlX6WkJd8sH2du4bjSFElzYz5P94G5qHVaotqWc6dhzbVZsQhUTFSEuzCQ1hxAWTJFSuJgJO7cqfxIYo0BWfiW1MOmIlKxbVxbhRKscQR4mWEFtW7eIkbCpk3zMPjnwIG1bOpMN5jbZXSGwWnK8GUUVwptf9NtRgZkC3B+ZVIwM69qkEZ4Pl/TUSwKQLulULeyQVb/OvZqPcCYuuSQye98620eJYPyqlHByYt35ImVI4hp/D3lB95lr29Ecj80A5RIrtgAkt81Id9cuxccuw8Ytu7+bMoaeRssTDWBLo/vDf0fFSgL1r/vG5RaabYcbPdcolsr2yG/3OLuW3sfx4FfuUigS8OMoRDWa63+aNS5mDo+5pWcXNoY4fJPUo1kTBnXXzWuqyFNYxqoljCFlE/o7zSsdJAzuS4iFhpNurZhcN7zEDQ8E1HqDuItuf595h9i++4lZN7JcRr83SRQxEse9HK+SuDxOG9Rqv6QDKIEFoWtUxgntmEumoh50s9NAojNPKkYI0IIXDwojaDt9mxlA=
    on_success: always
    template:
      - "Repo %{repository_slug} %{result} build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch %{branch}."
      - "Execution time: %{duration}"
      - "Message: %{message}"
install:
- yarn install
jobs:
  include:
    - stage: "Lint, Test and Build"
    - script: yarn lint && yarn test && yarn generate
    - stage: "Staging"
    - script: yarn generate:prod
      deploy:
        provider: firebase
        skip_cleanup: true
        token:
          secure: $FIREBASE_TOKEN
        project: "nwhacks-2019"
        on:
          branch: dev
    - stage: Deploy
      script: yarn generate:prod && echo "cmd-f.nwplus.io" >> dist/CNAME
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: dist
        on:
          branch: master
stages:
- Lint, Test and Build
- name: Staging
  if: branch = dev
- name: Deploy
  if: branch = master
